In [4]:
import pandas as pd
import pyLDAvis
import pyLDAvis.lda_model
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.datasets import fetch_20newsgroups
# 데이터 로드
data = fetch_20newsgroups(subset='train', remove=('headers', 'footers', 'quotes'))
documents = data.data

In [5]:
df_120text = pd.read_csv("https://raw.githubusercontent.com/corazzon/web_scraping/master/seoul-120/seoul-120-text.csv")
df_120text[:3]

번호  분류                 제목  \
0  2645  복지        아빠 육아휴직 장려금   
1  2644  경제  [서울산업진흥원] 서울메이드란?   
2  2643  환경          (강북구) 정비중   

                                                  내용      내용번호  
0  아빠 육아휴직 장려금   업무개요  남성근로자의 육아휴직을 장려하고 양육에 따른 경...  23522464  
1  서울산업진흥원 서울메이드란 서울의 감성을 담은 다양하고 새로운 경험을 제공하기 위해...  23194045  
2  강북구 정비중  업무개요  투명 폐트병을 교환보상하므로 수거율을 높이고 폐기물을 감...  23032485

In [6]:
tfidfVectorizer = TfidfVectorizer(stop_words='english', max_df=0.95 ,min_df=2)

In [7]:
tfidf_documents = tfidfVectorizer.fit_transform(documents)
tfidf_documents.toarray()[:1]

array([[0., 0., 0., ..., 0., 0., 0.]])

In [8]:
tfidf_documents.toarray().shape

(11314, 39115)

In [9]:
import numpy as np
np.where(tfidf_documents.toarray()[:1]>0)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([ 2582,  2918,  4348,  7279,  7618,  7843,  8160,  8308, 11269,
        12709, 12710, 13133, 13725, 13755, 15821, 17670, 18895, 20611,
        20958, 21663, 21665, 22151, 23553, 27879, 29041, 29858, 30936,
        31406, 32237, 32669, 32807, 37946, 38743]))

In [11]:
latentDirichletAllocation_3 = LatentDirichletAllocation(n_components=3, n_jobs=-1)

In [12]:
latentDirichletAllocation_5 = LatentDirichletAllocation(n_components=5, n_jobs=-1)

In [13]:
latentDirichletAllocation_7= LatentDirichletAllocation(n_components=7, n_jobs=-1)

In [15]:
LDA3 = latentDirichletAllocation_3.fit(tfidf_documents)
LDA5 = latentDirichletAllocation_5.fit(tfidf_documents)
LDA7 = latentDirichletAllocation_7.fit(tfidf_documents)

In [16]:
vis3 = pyLDAvis.lda_model.prepare(LDA3, tfidf_documents, tfidfVectorizer)
vis5 = pyLDAvis.lda_model.prepare(LDA5, tfidf_documents, tfidfVectorizer)
vis7 = pyLDAvis.lda_model.prepare(LDA7, tfidf_documents, tfidfVectorizer)

In [17]:
pyLDAvis.enable_notebook()
pyLDAvis.display(vis3)

In [18]:
pyLDAvis.enable_notebook()
pyLDAvis.display(vis5)

In [19]:
pyLDAvis.enable_notebook()
pyLDAvis.display(vis7)